### PR TITLE
Oric-1/Atmos/Telestrat port

### PR DESCRIPTION
**Pull request by iss000**
Added Oric-1/Atmos/Telestrat port by [raxiss].

### CODE REVIEW

**Comment by StewBC** [comment]
Awesome :)

**Comment by iss000** [comment]
> Awesome :)

Thanks for accepting the port!
FYI, full finished cc65-Chess for Oric (with intro and credits) is available at [DF Oric forum](http://forum.defence-force.org/viewtopic.php?f=20&t=2110).

**Comment by StewBC** [comment]
I have no experience with, or really any knowledge of, Oric computers.  I had to go build Oricutron.  A whole new journey awaits me :)  I have played your version of the chess though and it's beautiful.

The sad truth is that it's a pretty terrible chess "engine".  Not long after I made it, I wanted to improve it by talking to someone that really plays chess.  When I wanted to implement some things this person told me, I discovered that the game corrupts the GameDB.  Since then I haven't gone back to look at it again but now that there are 2 really nice versions, I probably should.  

I should probably also do something about the ugly C64 version ;)   I am a little busy right now but I'll put all that on the list.  Anyway, great job with the Oric version - it's really pretty.

**Comment by StewBC** [comment]
I have a question.  oric doesn't seem to be a valid target.  If I set the target to telestrat it doesn't build with "Unresolved external '__BASHDR__' referenced in: src/telestrat/oric.cfg(3)".  If I set it to atmos, that does work.  Is it okay if I rename the src/oric to src/atmos and rename the target to atmos or is there something I am missing about a supported target named oric?

**Comment by iss000** [comment]
There will be no problem with renaming 'oric' to 'atmos'! I didn't used 'atmos' because I wanted to make it clear that it's compatible with Oric-1 too ;). But in general and from cc65's point of view it's totally OK to use 'atmos'. The result will remain Oric-1 compatible. 
BTW, little change in 'readme.txt' is needed:
`make TARGETS=atmos OPTIONS=optspeed tap`

**Pull request merged**
